name: cse6250_final_project
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cpuonly=2.0
  - expat=2.7.1
  - filelock=3.17.0
  - freetype=2.13.3
  - fsspec=2025.7.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.5.0
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=3.0
  - numpy-base=1.26.4
  - openjpeg=2.5.4
  - openssl=3.0.18
  - opentelemetry-api=1.37.0
  - pillow=11.1.0
  - python=3.10.19
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - readline=8.3
  - setuptools=80.9.0
  - sleef=3.5.1
  - sqlite=3.50.2
  - sympy=1.14.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - comet-ml==3.54.0
      - configobj==5.0.9
      - dulwich==0.24.7
      - everett==3.1.0
      - flatbuffers==25.9.23
      - gast==0.4.0
      - google-auth==2.42.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.15.1
      - idna==3.11
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==2.13.1
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - numpy==1.23.5
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==1.5.3
      - pip==25.3
      - protobuf==3.20.3
      - psutil==7.1.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - scikit-learn==1.0.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentry-sdk==2.43.0
      - simplejson==3.20.2
      - six==1.17.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-macos==2.13.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tqdm==4.66.5
      - typing-extensions==4.5.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==2.0.0
      - wurlitzer==3.1.1
      - wandb==0.23.0
